Readme update (badges + description)

diff --git a/.github/workflows/dockerimage.yml b/.github/workflows/dockerimage.yml
--- a/.github/workflows/dockerimage.yml
+++ b/.github/workflows/dockerimage.yml
@@ -70,41 +70,52 @@ jobs:
       #- name: Database Check
       #  run: docker-compose exec -T php bin/console doctrine:schema:validate
       - name: Security Checks
-        run: docker-compose exec -T php composer req sensiolabs/security-checker
+        run: |
+          curl -L -sS --output local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64
+          chmod +x ./local-php-security-checker
+          ./local-php-security-checker --path ./api/composer.lock
+
+      - uses: codecov/codecov-action@v1
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
+          name: codecov-umbrella
+          fail_ci_if_error: true
+          verbose: true
       #- name: Run Postman Tests
       #  if: contains( github.ref, 'master' ) == false && contains( github.base_ref, 'master' ) == false
       #  run: newman run api/public/schema/*.postman_collection.json
-      #            - name: Add docker tags
-      #              if: github.ref == 'refs/heads/master'
-      #              run: |
-      #                  images=$(docker-compose images -q | xargs docker inspect --format='{{ index .RepoTags 0}}' | cut -d':' -f1 | grep $APP_NAME_TECHNICAL)
-      #                  for image in $images
-      #                  do
-      #                    docker tag "${image}":latest "${image}":"${APP_BUILD}"
-      #                  done
-      #                  echo 'IMAGES=$images' >> $GITHUB_ENV
+      - name: Add docker tags
+        if: github.ref == 'refs/heads/master'
+        run: |
+          images=$(docker-compose images -q | xargs docker inspect --format='{{ index .RepoTags 0}}' | cut -d':' -f1 | grep $APP_NAME)
+          for image in $images
+          do
+            docker tag "${image}":latest "${image}":"${APP_BUILD}"
+          done
+          echo 'IMAGES=$images' >> $GITHUB_ENV
       - name: Show all images
         run: docker images
-      - name: Login to DockerHub Registry
-        id: dockerhub-login
+      - name: Login to Container Registry
+        id: containerregistry-login
         run: |
-          if [ "${{ secrets.DOCKERHUB_PASSWORD }}" != "" ] && [ "${{ secrets.DOCKERHUB_USERNAME }}" != "" ]; then
-            echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
-            echo "##[set-output name=success;]true"
-          else
-            echo "##[set-output name=success;]false"
-          fi
-      - if: steps.dockerhub-login.outputs.success == 'true' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/development')
-        name: Push to docker hub
+         if [ "${{ secrets.CR_PAT }}" != "" ]; then
+           echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $(cut -d'/' -f1 <<< $GITHUB_REPOSITORY) --password-stdin
+           echo "##[set-output name=success;]true"
+         else
+           echo "##[set-output name=success;]false"
+         fi
+      - if: steps.containerregistry-login.outputs.success == 'true' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/development')
+        name: Push to Container Registry
         run: docker-compose push
-      #            - if: steps.dockerhub-login.outputs.success == 'true' && github.ref == 'refs/heads/master'
-      #              name: Push versioned containers to Docker Hub
-      #              run: |
-      #                  images=$(docker-compose images -q | xargs docker inspect --format='{{ index .RepoTags 0}}' | cut -d':' -f1 | grep $APP_NAME)
-      #                  for image in $images
-      #                  do
-      #                    docker push "${image}":"${APP_BUILD}"
-      #                  done
+
+      - if: steps.containerregistry-login.outputs.success == 'true' && github.ref == 'refs/heads/master'
+        name: Push versioned containers to Container Registry
+        run: |
+          images=$(docker-compose images -q | xargs docker inspect --format='{{ index .RepoTags 0}}' | cut -d':' -f1 | grep $APP_NAME)
+          for image in $images
+          do
+            docker push "${image}":"${APP_BUILD}"
+          done
       - name: Create kube config
         id: kubeconfig
         if: contains( github.ref, 'development' )
@@ -115,6 +126,18 @@ jobs:
           else
             echo "##[set-output name=success]false"
           fi
+      - name: Rollout new containers
+        if: (contains( github.ref, 'development' )) && steps.kubeconfig.outputs.success == 'true' && success()
+        run: |
+          kubectl rollout restart deployment/$APP_NAME-php --kubeconfig="kubeconfig.yaml"  --namespace=$APP_ENV
+          kubectl rollout restart deployment/$APP_NAME-nginx --kubeconfig="kubeconfig.yaml"  --namespace=$APP_ENV
+          kubectl rollout restart deployment/$APP_NAME-varnish --kubeconfig="kubeconfig.yaml"  --namespace=$APP_ENV
+      #            - name: Export release code
+      #              if: (success() || failure())
+      #              id: releasecode
+      #              run: |
+      #                  export RELEASE=$APP_BUILD-$(git rev-parse --short $GITHUB_SHA)
+      #                  echo "##[set-output name=releasename]$RELEASE"
       - name: Print release name
         if: (success() || failure())
         run: echo $RELEASENAME
